project_id = "tamay-enterprises-management"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/reset-password", "https://*.vercel.app/reset-password"]

[storage]
enabled = true
